### ISSUE TITLE
[Vanilla Bug] WW's `XSurface_BlitPart` function is not thread-safe

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#163]
### Description:
According to dkeeton, WW's `XSurface_BlitPart` is not thread-safe. I guess that can lead to crashes when running the game with multiple cores?

### Additional Files:
CnCNet ts-patches has code to force the game to use ddraw.dll's blit function instead of WW's custom one: https://github.com/CnCNet/ts-patches/blob/master/src/video_mode_hacks.asm#L81
```x86asm
;;; This will force the game to always use ddraw's blit function rather than WW blit.
;;; We're avoiding ww blit functions because they are not thread safe
@SET 0x0048B70E, { mov bl, 0 }
```

**Comment by CCHyper** [comment]
I think it would be best to outright reimplement this function to only use the DirectDraw case, that way we eliminate any possible edge case where this could fail. We should have this function code available already to be able to do this.

**Comment by tomsons26** [comment]
So the problem with patching to only use DirectDraw is there are various scenarios where Blt fails, this is why the software blitter exists.
One scenario is if the source and destination surface bit depths don't match, XSurface Blitter will convert them, DirectDraw Blt fails to blit.

I THINK, not entirely sure, another scenario is when the source surface is XSurface, destination is DSurface, DirectDraw can't Blit to a non DirectSurface.

Yes there are 8 bit surfaces in the game. For example voxels and cloak range use 8 bit, some font code uses 8 bit, Dropship Loadout cameos use 8 bit, Ion blast is 8 bit, so is spotlight circle, mouse, likely other things i missed.
It's very likely at least one of these things is broken with this hack.

The origin of a another thread Blit would likely be the Mouse, the mouse since TD days runs in a separate thread.
Can't at least right now think of another thread that would blit.

**Comment by Rampastring** [comment]
> For example voxels and cloak range use 8 bit, some font code uses 8 bit, Dropship Loadout cameos use 8 bit, Ion blast is 8 bit, so is spotlight circle, mouse

I haven't noticed any of those looking off.

**Comment by CCHyper** [comment]
I'm closing this for now. We can reopen this if some crash reports come forward relating to this in the future.
