### ISSUE TITLE
[New Feature] Sorted sidebar cameos

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#197]
### Description:
The order of cameos in vanilla TS is determined by the order that you access technology in. In some situations, like when you fully tech up, then lose some of your mid-way tech later on, and then gain access to the mid-way tech again, this can result in the sidebar cameos being in an unintuitive order.

Likewise, if you lose your barracks and rebuild it later while already having a weapons factory, your infantry cameos will be below your vehicle cameos. Most players find this confusing.

### Possible Implementation:
CnCNet ts-patches implements cameo sorting for both sidebar strips. However, the community has wanted to be able to customize the sorting per-strip. I propose adding a couple of Rules.ini keys for this:

```
[General]
SortSidebarStructureStrip=true/false
SortRightSidebarStrip=true/false
```

### Additional Files:
CnCNet ts-patches implementation, sorting the cameos with qsort:
https://github.com/CnCNet/ts-patches/blob/master/src/mods/sidebar_cameo_sort.asm
https://github.com/CnCNet/ts-patches/blob/master/src/mods/sidebar_cameo_sort_helper.c

**Comment by CCHyper** [comment]
@Rampastring:
Would it not be better to add these options to SUN.INI? this makes it completely a user choice then. We could also add a new radio button to the in-game options dialog such as "Sort Sidebar"?

Also, this patch is done in `BuildingClass::Update_Buildables`, I wonder if it would be best done in `SidebarClass::Add`, especially since it's dealing with protected members. This would also eliminate the repetitive patches.
