### ISSUE TITLE
[New Feature] Allow changing default value of `WalkFrames`

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#216]
### Description:
From CnCNet ts-patches / DTA:

```
@SET 0x0065B9E6, {mov byte [esi+4D0h], 1} ;byte ptr
@SET 0x0065BF3D, {mov [esi+21h], eax}
```

**Comment by CCHyper** [comment]
While I can understand that this would remove the need for adding `WalkFrames=1` to all the definitions in ART.INI, this seems like a bespoke item for DTA and not of much use to other mods in general.

Because of this, I'm going to close this issue on the basis that adding `WalkFrames=1` to the ART.INI definitions would take a matter of minutes to do and that there is no requirement for this change of behaviour.
