### ISSUE TITLE
[New Feature] Seeing all queued action lines

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#38]
### Description:
Tiberian Sun allows you to queue many move orders for a unit with the Q key. However, the game only draws the action line for the current move order and there is no visual indication that you have more moves queued. It would make the Q feature clearer if all the action lines were drawn. CnCNet TS has this implemented in a way that by default the game only displays the current move order, but you can see all the action lines by holding Q (which also means that you see the action lines for all queued orders as you assign them). CnCNet TS can also display the TarCom line and movement order lines separately, which is nice for turreted vehicles that can move and shoot at the same time.

### Possible Implementation:
CnCNet ts-patches implementation: https://github.com/CnCNet/ts-patches/blob/master/src/draw_all_action_lines.asm

Screenshot of this in action in DTA. The MCV was given multiple queued move orders.
![Action lines](https://cdn.discordapp.com/attachments/826473223276986409/839924454427328542/allactionlines.png "Action lines")

**Comment by CCHyper** [comment]
I think this would be best behind a new SUN.INI key, just like `UnitActionLines`. I guess `QueueMoveLines` and `TargetLines`.

**Comment by Bittah** [comment]
I'm not sure if you'd prefer this as a separate issue, but it'd be nice if you could create a Q-move loop (similar to how you can do that with unit rally points in RA2). This way you wouldn't need to keep using waypoints when you only want to set up a temporary patrol and players will do it more often since it'll be less annoying to do so.

The main thing missing compared to when you use waypoints then would be guard-move, so the ability to guard-Q-move (Ctrl+Alt+Q) would likely also be necessary for this to be effective (currently Q gets ignored when you attempt to give an order while holding Ctrl+Alt+Q and the unit will only perform the guard move).

**Comment by Rampastring** [comment]
> I'm not sure if you'd prefer this as a separate issue, but it'd be nice if you could create a Q-move loop (similar to how you can do that with unit rally points in RA2). This way you wouldn't need to keep using waypoints when you only want to set up a temporary patrol and players will do it more often since it'll be less annoying to do so.

RA1 has code for q-move loops, but it's a bit bugged and so doesn't work. I wouldn't be surprised if the case was identical still in TS.

This commit in my "More QoL Improvements" mod for RA1 enabled q-move loops: https://github.com/Rampastring/CnC_Remastered_Collection/commit/c13d799df17d29a3f626c53fa4be0fd96e235fd9

**Comment by ZivDero** [comment]
Resolves in a6c7d596b1f03e80437d41c6ad12454b9db12ae1
