### ISSUE TITLE
[Vanilla Bug] Placing down a building upgrade instantly repairs the parent building

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#873]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

As the title says, placing an upgrade on a damaged building instantly reverts the building to full health. This also applies to preplaced, pre-upgraded structures on the map.

### Steps To Reproduce

1. Build a building that can be upgraded: GDI Power Plant, Component Tower, etc.
2. Damage the building.
3. Place an upgrade on the building.

### Expected Behaviour

The building remains damaged.

### Actual Behaviour

The building is reverted to full health.

### Additional Context

This is likely a well-known bug in the game, meaning players know how to abuse it. Therefore it might require a toggleable option.

**Comment by CCHyper** [comment]
This actually seems to be a "feature" rather than a bug...

I located the code that does the restoration of the building's health, and removing it exposes a bug where the animations do not get drawn on the building once placed. So I think it's safe to assume that this "feature" was done as a bug fix to hide the aforementioned issue.

I'll close this for now, if it's ever looked into and the base bug is fixed, we can reopen it.
